### ISSUE TITLE
Add notes of status on README

### ISSUE THREAD

**Issue by onacit** [vladmihalcea/tsid#11]
First of all, Thank you for your efforts.

Would you please add notes of
* current status of this module
* or distinguishing features against the [TSID-Creator](https://github.com/f4b6a3/tsid-creator/)
?

That might help many developers for selecting their dependencies.

Thank you, again.

**Comment by vladmihalcea** [comment]
At the moment, [the commit history](https://github.com/f4b6a3/tsid-creator/compare/master...vladmihalcea:hypersistence-tsid:master) can tell you the difference between the original and thus fork.
