### ISSUE TITLE
Node ID out of range when the tsid.node is larger than 255

### ISSUE THREAD

**Issue by postalservice14** [vladmihalcea/tsid#19]
Beacsuse of these guys:

```java
public static final Factory INSTANCE_256 = newInstance256();

public static final Factory INSTANCE_1024 = newInstance1024();

public static final Factory INSTANCE_4096 = newInstance4096();
```

Whenever the Factory is instantiated, these factories are instantiated and when it pulls the `tsid.node` number from the system property, it fails with "Node ID out of range"

Here's a test that causes it to happen:

```java
@Test
public void testWithNodeBitsSetFromProperty() {
	final int randomBits = 22;
	// test all allowed values of node bits
	for (int i = 20; i >= 0; i--) {
		final int nodeBits = i;
		final int counterBits = randomBits - nodeBits;
		final int node = (1 << nodeBits) - 1; // max: 2^nodeBits - 1
		System.setProperty(NODE, String.valueOf(node));
		System.setProperty(NODE_COUNT, String.valueOf(1 << nodeBits));
		TSID tsid = TSID.Factory.builder().withNodeBits(nodeBits).withNode(node).build().generate();
		int actual = (int) tsid.getRandom() >>> counterBits;
		assertEquals(node, actual);
	}
}
```

**Comment by vladmihalcea** [comment]
The `Node ID` takes from 0 to 20 bits, so if you provide a larger than `1048576`, it will fail.

**Comment by postalservice14** [comment]
@vladmihalcea  - my test is running from 0 to 20 node bits and it fails without my PR change.  It is not providing a value larger than 1048576.  Am I missing something?  Thank you!

**Comment by vladmihalcea** [comment]
@postalservice14 Yes, you're right about that. I will have to think about a solution to fix it without removing those instances.

I'm thinking of doing something like this:

    node = Math.floorMod(node, max);

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by fabiolimace** [comment]
I arrived here late.

But if you are still open to suggestions:

https://gist.github.com/fabiolimace/a6110a1490b93e99accd0cfc4a004e6a

The `Proxy` class works as a [lazy loading](https://en.wikipedia.org/wiki/Lazy_loading) technique.

The immediate downside is that you need to remove the `final` keyword from `Factory`.

**Comment by vladmihalcea** [comment]
Thanks for the tip.
