### ISSUE TITLE
Shift the thread id into the random part

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/tsid#2]
Allow the bits of the thread id part to precede the random bits.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by thadguidry** [comment]
@vladmihalcea Hi Vlad, what was the reasoning here?  To make thread id collisions less likely?  In which scenarios?  Or was this change because of some other problem you saw?  Curious, if you could explain the problem itself and the reasons for this change.  Thanks!

**Comment by vladmihalcea** [comment]
The reason was to avoid collisions even more since each thread identifier is unique.

**Comment by thadguidry** [comment]
Great...OK, understand.

And in https://github.com/vladmihalcea/hypersistence-tsid/commit/8568e830aef27c0f3a5fb0e202e17daf36682c3d

Could you explain, generally, the changes that happened in that commit ?
1. When you say "reduce sync scope" did that generally mean reduce the amount of thread synchronization that was happening to improve performance where you could, or were the changes in that commit to generally avoid more collisions and at what level?
2. Also, `// one generator shared by ALL THREADS` comment was removed and the code changes here. So are there now multiple generators spawning multiple threads per node potentially?  Not quite understanding the code completely.

Also, thanks for your efforts on maintaining this package!  Would like to sponsor you, but you don't have your GitHub sponsorship setup on this repo, or your org name yet.  If you could do that, then I'd be happy to throw you a few dollars per month. Thanks again for maintaining this!

**Comment by vladmihalcea** [comment]
Yes, that commit removes the thread contention on the `generate` method. As for the test case, in the original version, there were no conflicts since the `generate` method was allowing a single thread to execute.

Since I removed the `synchronized`, I wanted to check the collisions while using multiple threads when the generator takes the `threadId` into consideration. As long as you set the `threadId`, there should not be collisions even without the previous  `synchronized`.

**Comment by thadguidry** [comment]
Awesome thanks for answering!
We're using your package in https://db2rest.com which might interest you and will publish a blog post on TSID generation.
Thanks bye for now!

**Comment by vladmihalcea** [comment]
Thanks. That website you linked in your comment does not work for me.

**Comment by thadguidry** [comment]
sorry, updated the link... .com not .org

also,
Also, thanks for your efforts on maintaining this package! Would like to sponsor you, but you don't have your GitHub sponsorship setup on this repo, or your org name yet. If you could do that, then I'd be happy to throw you a few dollars per month. Thanks again for maintaining this!

**Comment by vladmihalcea** [comment]
Thanks. I don't use GitHub sponsor, but I have this [Coaching Basic](https://vladmihalcea.teachable.com/p/high-performance-java-persistence-coaching-basic) package that could be used for the same purpose.

**Comment by thadguidry** [comment]
Thanks, well, I was thinking a "few" dollars, not quite that "many" per month. :-)

**Comment by vladmihalcea** [comment]
@thadguidry You can cancel the subscription any time and pay as much as you want. For instance, if you wanted to donate $4 a month for 12 years, then it's the same as buying one month of this Basic Coaching and cancel your subscription after one payment. 

However, don't worry about it. I only offered this alternative because you wanted to sponsor it.

**Comment by thadguidry** [comment]
Done! (I'll cancel after 1 month)

**Comment by vladmihalcea** [comment]
Thanks and stay tuned for more.
