### ISSUE TITLE
Javscript function to generate TSIDs?

### ISSUE THREAD

**Issue by sbutler-gh** [vladmihalcea/tsid#3]
I want to generate TSIDs in a javascript client and store them as Primary Keys in a postgres database (Supabase) — probably as BIGINTs, per the guidance [here](https://vladmihalcea.com/uuid-database-primary-key/)

Is it possible to provide some simple guidance for how to use generate TSIDs using javascript in a vanilla HTML/JS client?

**Comment by vladmihalcea** [comment]
This is a Java library. For JavaScript, you'd have to adapt the logic to a JavaScript function.
