### ISSUE TITLE
TSID is not thread-safe

### ISSUE THREAD

**Issue by HalfLegend** [vladmihalcea/tsid#5]
Test case in Kotlin:
```
    @Test
    fun testParallelCollision() {
        val countPerThread = 10000
        val threadCount = 100
        val totalCount = countPerThread * threadCount

        val barrier = CyclicBarrier(threadCount)
        val pool = Executors.newCachedThreadPool()
        val results = LongArray(totalCount)
        val allJobs: Array<CompletableFuture<*>?> = Array(threadCount) { null }
        for (i in 0..<threadCount) {
            allJobs[i] = CompletableFuture.runAsync({
                val upper = (i + 1) * countPerThread
                val lower = i * countPerThread
                barrier.await()
                // val start = System.currentTimeMillis()
                for (j in lower..<upper) {
                    results[j] = TSID.Factory.getTsid().toLong()
                }
            }, pool)
        }
        CompletableFuture.allOf(*allJobs).get()
        val distinctCount = results.asSequence().distinct().count()
        println(distinctCount)
        assert(distinctCount == totalCount)
    }
```
result:  996438
java.lang.AssertionError: Assertion failed

`generate()` is **NOT** thread-safe because it is not `synchronized`

in TSID.java: 
```
public TSID generate() {
	final long _time = getTime() << RANDOM_BITS;
	final long _node = (long) this.node << this.counterBits;
	final long _counter = (long) this.counter & this.counterMask;
	return new TSID(_time | _node | _counter);
}


private synchronized long getTime() {
    // ...
    // the value of counter is changed

```

The value of `counter` is changed in `getTime()` which is `synchronized`.
However, the value of `counter` is used in `generate()` which is not `synchronized`.

In `generate()` method: at the instant after `getTime()`,  the value of `counter` is 5 for example, but when it comes to `final long _counter = (long) this.counter & this.counterMask;`, `counter` might be changed to 6 by another thread, which is unexpected.

**Comment by pkernevez** [comment]
I think we have the same problem.
I reproduce it with some logs (see https://github.com/pkernevez/hypersistence-tsid/tree/add-logs ).

And I finally have one collision with exactly the issue described in this issue:
```
Thread=batch-4, clock=1715291030827, lastTime=1715291030827, counterBefore=23004, carry=0, counterNew=23005, newTime=1715291030827 | AFTER, time=576524830174609408, counter=23005, 0G01T8X5D2PEX
Thread=batch-5, clock=1715291030827, lastTime=1715291030827, counterBefore=23003, carry=0, counterNew=23004, newTime=1715291030827 | AFTER, time=576524830174609408, counter=23005, 0G01T8X5D2PEX
2024-05-09T23:43:50.828+02:00  INFO 51971 --- [        batch-4] [663d43965a61c73cfcd121f88cc1381f-10f7f22a072bdef7] s.c.p.d.AccountingEntity : Creating AccountingPositionSnapshotEntity with id=0G01T8X5D2PEX
2024-05-09T23:43:50.828+02:00  INFO 51971 --- [        batch-5] [663d43965a61c73cfcd121f88cc1381f-653b7278300d5291] s.c.p.d.AccountingEntity : Creating AccountingPositionSnapshotEntity with id=0G01T8X5D2PEX
```
In the generate method, the thread 5 read the new value set by thread 4.

**Comment by vladmihalcea** [comment]
You should not get these collisions when using the threadId into the generated value, as demonstrated by [this commit](https://github.com/vladmihalcea/hypersistence-tsid/commit/8568e830aef27c0f3a5fb0e202e17daf36682c3d).

**Comment by pkernevez** [comment]
As I said in the issue #15, this test is failing often on my laptop.

I'm not clear about the strategy of the factory about multithreading.

In the test pointed by [your commit](https://github.com/vladmihalcea/hypersistence-tsid/commit/8568e830aef27c0f3a5fb0e202e17daf36682c3d) you create on factory per thread. If it's the strategy, why do you have 'synchronizes' in `getTime` method ?

**Comment by vladmihalcea** [comment]
The failing test can be ignored. The other one that sets the threadId per node is the one that matters.

Now, the generation doesn't have to be thread safe. If you set the threadId, you don't need to make the whole generate method synchronized.

The getTime has to be synchronized because it has to be monotonocally increasing.

**Comment by pkernevez** [comment]
But your still have a collision risk (and we have an issue with this). With my PR proposal, you don't change the scope of synchronise and put the collision risk to 0 (at least, I think so).

**Comment by vladmihalcea** [comment]
If you set the threadId, there is no collision risk with or without that change. 

However, I will check whether the counter has to be included as well in the synchronized block since its purpose was more for ensuring the monoticity of time.

**Comment by pkernevez** [comment]
The strategy used by testCollisionOneThreadPerNode (ie use the withNode( ) with threadId) is not so simple as:
* we already use withNode( ...) for our nodes in the cluster. I think we can merge them to create a 'new id' and deal with this point.
* we are not directly creating the threads like in your test, threads a managed by pools created by SpringBoot (at least 3 pools at the moment: HTTP, Scheduler and custom pool for spring batch). That means intercept all the creation/destruction of threads, give them a sharedId to be use in the Factories.

**Comment by pkernevez** [comment]
If the idea is to have one factory per thread, why do we need a `synchronize` in the `getTime` method ?
If we want to share the factory instance between threads (that is my understanding with the readme examples) we can remove the need of using a threadId by including counter in the `synchronize` scope.

**Comment by vladmihalcea** [comment]
That's not the idea. You are drawing conclusions based on a test case that should have been ignored. 

Check out the TSID class for more details about how it's used, not the failing test that you should have ignored.

**Comment by pkernevez** [comment]
My understanding of the examples and the implementation of TSID is to have a singleton shared by all threads.
And `getTime` implementation is dealing with concurrency with the `synchronize` keyword.
But the counter is re-read outside of this synchronize bloc. As explain in this issue and shows in my initial comment, we can read in the `generate` method invalid values that were modified in the synchronize `getTime` method. Both reads and writes have to be synchronized.

**Comment by fabiolimace** [comment]
I also think the problem is caused by the counter being accessed outside of the synchronized block, when it could have been updated by another thread after the call to `getTime()`.

I once had a headache because of it. Then I gave up and put the synchronized keyword in the entire generation method.

Another thing that could be done, in my opinion, is to replace the `synchronized` keyword with `ReentrantLock()` to better handle [pinned virtual threads](https://medium.com/@phil_3582/java-virtual-threads-some-early-gotchas-to-look-out-for-f65df1bad0db).

According to Oracle's [documentation](https://docs.oracle.com/en/java/javase/21/core/virtual-threads.html#GUID-704A716D-0662-4BC7-8C7F-66EE74B1EDAD):

> Pinning does not make an application incorrect, but it might hinder its scalability. Try avoiding frequent and long-lived pinning by revising synchronized blocks or methods that run frequently and guarding potentially long I/O operations with java.util.concurrent.locks.ReentrantLock.

---
EDIT: I deleted a suggestion that doesn't work.

**Comment by vladmihalcea** [comment]
A `ReentrantLock` guarding the time and counter variable assignment would be the best approach.

I'll do that and modify the test that fails to use the generate method instead. If the generation is thread-safe for those two variables, I suppose we should not see any conflict even without the threadId trick.

**Comment by pkernevez** [comment]
I have an additional question:
* if we have multi-threaded implementation
* if we use only one factory per node
Is there a reason to not use a 'random' function like `()->0` instead of the existing ones ?
Such implementation will avoid the case with cary (it will use only if all the values for the current millisecond are used).

**Comment by vladmihalcea** [comment]
Fixed.
