### ISSUE TITLE
Difficulty in storing TSIDs as `long` but serving their `String` representations to Javascript clients

### ISSUE THREAD

**Issue by lewis-munene** [vladmihalcea/tsid#8]
While it is preferable to store TSIDs using `long` data type as compared to `String` (Varchar), since `long` is more compact (64 bits only), it is not practical while working with Javascript clients since long numbers are truncated to fit the Javascript INT_MAX value.

One possible way to achieve the best of both worlds is to store longs but serve Strings, but this would mean doing the conversion at every API interaction point and it's also more difficult to troubleshoot in case there are bugs in the API.

Another way is to simply store Strings and serve Strings but you use up at least 5 bytes more per table record.

@vladmihalcea have you found any fool-proof way to ensure a consistent API (i.e. store `long`, serve `long`) while working with Javascript clients?

**Comment by vladmihalcea** [comment]
@lewimuchiri There are two ways you can address this issue:

1. Using JavaScript [BigInt](https://www.w3schools.com/js/js_bigint.asp)
2. Storing long and exporting them as String to avoid the maximum Integer limitation

**Comment by lewis-munene** [comment]
Thank you for your response.

The problem with the BigInt idea is that if you're using a library to deserialize API responses from the server then you'll receive already truncated ids. Most client-side libraries will not give you the chance to determine the data types of the fields when doing deserialization (especially if you're deserializing to json objects). But I suppose you can look for a library that gives you that option. 

Option 2 is a viable option but it makes it difficult to debug and troubleshoot issues (since the way ids are stored is different from how they are presented) and also, if you're using GraphQL APIs such as Elide, it will be impossible to work with it like this since such APIs do not give you any leeway to do the conversion from string to long without tweaking the library.

I settled for storing them as strings and serving strings to the clients. That was the only painless way I could work with TSID.
Thanks
