### ISSUE TITLE
Support for reactive

### ISSUE THREAD

**Issue by MiguelAngelOne** [vladmihalcea/tsid#9]
Hello, I was reading the [hibernate-reactive2.0](https://hibernate.org/reactive/documentation/2.0/reference/html_single/ ) documentation and the annotation TsidGenerator should implement the ReactiveIdentifierGenerator interface in order to support reactive environment.

I think it can be a great addition to have a @Tsid for reactive environments.

**Comment by vladmihalcea** [comment]
The library only generates TSID values. Hypersistence Utils provides the Hibernate identifier generator for Hibernate ORM. Hypersistence Utils cannot use Hibernate Reactive as you'd need a new library for that.
